project_id = "tnavetydxwkguwohcrcp"

[functions.create-request]
verify_jwt = false

[functions.get-request]
verify_jwt = false

[functions.generate-proposals]
verify_jwt = false

[functions.stylepack-sign-upload]
verify_jwt = false

[functions.check-style-compatibility]
verify_jwt = false

[functions.generate-proposals-v2]
verify_jwt = false

[functions.stylepack-analyze]
verify_jwt = true

[functions.stylepack-quick-test]
verify_jwt = true

[functions.generate-embeddings]
verify_jwt = true

[functions.search-similar-styles]
verify_jwt = false

[functions.generate-layout-mask]
verify_jwt = true

